package br.com.financeiro.pojo;

// default package
// Generated 10/11/2014 22:21:36 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClienteFornecedor generated by hbm2java
 */
@Entity
@Table(name = "cliente_fornecedor")
public class ClienteFornecedor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String razao;
	private String fantasia;
	private String cnpj;
	private String cpf;
	private String ie;
	private String im;
	private Set<Movimento> movimentos = new HashSet<>(0);
	private Set<Endereco> enderecos = new HashSet<>(0);
	private Set<Contato> contatos = new HashSet<>(0);

	public ClienteFornecedor() {
	}

	public ClienteFornecedor(String razao, String fantasia, String cnpj,
			String cpf, String ie, String im) {
		this.razao = razao;
		this.fantasia = fantasia;
		this.cnpj = cnpj;
		this.cpf = cpf;
		this.ie = ie;
		this.im = im;
	}

	public ClienteFornecedor(String razao, String fantasia, String cnpj,
			String cpf, String ie, String im, Set<Movimento> movimentos, Set<Endereco> enderecos,
			Set<Contato> contatos) {
		this.razao = razao;
		this.fantasia = fantasia;
		this.cnpj = cnpj;
		this.cpf = cpf;
		this.ie = ie;
		this.im = im;
		this.movimentos = movimentos;
		this.enderecos = enderecos;
		this.contatos = contatos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "razao", nullable = false, length = 200)
	public String getRazao() {
		return this.razao;
	}

	public void setRazao(String razao) {
		this.razao = razao;
	}

	@Column(name = "fantasia", nullable = false, length = 100)
	public String getFantasia() {
		return this.fantasia;
	}

	public void setFantasia(String fantasia) {
		this.fantasia = fantasia;
	}

	@Column(name = "cnpj", nullable = false, length = 13)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "cpf", nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "ie", nullable = false, length = 8)
	public String getIe() {
		return this.ie;
	}

	public void setIe(String ie) {
		this.ie = ie;
	}

	@Column(name = "im", nullable = false, length = 8)
	public String getIm() {
		return this.im;
	}

	public void setIm(String im) {
		this.im = im;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "clienteFornecedor")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "clienteFornecedor")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "clienteFornecedor")
	public Set<Contato> getContatos() {
		return this.contatos;
	}

	public void setContatos(Set<Contato> contatos) {
		this.contatos = contatos;
	}

}
