package br.com.financeiro.pojo;

// default package
// Generated 10/11/2014 22:21:36 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContaBancaria generated by hbm2java
 */
@Entity
@Table(name = "conta_bancaria")
public class ContaBancaria implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int id;
	private Empresa empresa;
	private long agencia;
	private long conta;
	private int digito;
	private String nome;
	private long saldoInicial;
	private Set<Movimento> movimentos = new HashSet<>(0);
	
	public ContaBancaria() {
	}

	public ContaBancaria(int id, Empresa empresa, long agencia, long conta,
			int digito, String nome, long saldoInicial) {
		this.id = id;
		this.empresa = empresa;
		this.agencia = agencia;
		this.conta = conta;
		this.digito = digito;
		this.nome = nome;
		this.saldoInicial = saldoInicial;
	}

	public ContaBancaria(int id, Empresa empresa, long agencia, long conta,
			int digito, String nome, long saldoInicial, Set<Movimento> movimentos) {
		this.id = id;
		this.empresa = empresa;
		this.agencia = agencia;
		this.conta = conta;
		this.digito = digito;
		this.nome = nome;
		this.saldoInicial = saldoInicial;
		this.movimentos = movimentos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "agencia", nullable = false, precision = 10, scale = 0)
	public long getAgencia() {
		return this.agencia;
	}

	public void setAgencia(long agencia) {
		this.agencia = agencia;
	}

	@Column(name = "conta", nullable = false, precision = 10, scale = 0)
	public long getConta() {
		return this.conta;
	}

	public void setConta(long conta) {
		this.conta = conta;
	}

	@Column(name = "digito", nullable = false)
	public int getDigito() {
		return this.digito;
	}

	public void setDigito(int digito) {
		this.digito = digito;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "saldo_inicial", nullable = false, precision = 10, scale = 0)
	public long getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(long saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "contaBancaria")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
