package br.com.financeiro.pojo;

// default package
// Generated 10/11/2014 22:21:36 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContaContabil generated by hbm2java
 */
@Entity
@Table(name = "conta_contabil")
public class ContaContabil implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Integer id;
	private PlanoDeContas planoDeContas;
	private String nome;
	private String codigo;
	private boolean tipo;
	private Set<Movimento> movimentos = new HashSet<>(0);

	public ContaContabil() {
	}

	public ContaContabil(PlanoDeContas planoDeContas, String nome,
			String codigo, boolean tipo) {
		this.planoDeContas = planoDeContas;
		this.nome = nome;
		this.codigo = codigo;
		this.tipo = tipo;
	}

	public ContaContabil(PlanoDeContas planoDeContas, String nome,
			String codigo, boolean tipo, Set<Movimento> movimentos) {
		this.planoDeContas = planoDeContas;
		this.nome = nome;
		this.codigo = codigo;
		this.tipo = tipo;
		this.movimentos = movimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "plano_de_contas_id", nullable = false)
	public PlanoDeContas getPlanoDeContas() {
		return this.planoDeContas;
	}

	public void setPlanoDeContas(PlanoDeContas planoDeContas) {
		this.planoDeContas = planoDeContas;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "tipo", nullable = false)
	public boolean isTipo() {
		return this.tipo;
	}

	public void setTipo(boolean tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "contaContabil")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
