package br.com.financeiro.pojo;

// default package
// Generated 10/11/2014 22:21:36 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoMovimento generated by hbm2java
 */
@Entity
@Table(name = "historico_movimento")
public class HistoricoMovimento implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Movimento movimento;
	private boolean liquidado;
	private boolean tipo;
	private long valor;
	private Date vencimento;

	public HistoricoMovimento() {
	}

	public HistoricoMovimento(Movimento movimento, boolean liquidado,
			boolean tipo, long valor, Date vencimento) {
		this.movimento = movimento;
		this.liquidado = liquidado;
		this.tipo = tipo;
		this.valor = valor;
		this.vencimento = vencimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "movimento_id", nullable = false)
	public Movimento getMovimento() {
		return this.movimento;
	}

	public void setMovimento(Movimento movimento) {
		this.movimento = movimento;
	}

	@Column(name = "liquidado", nullable = false)
	public boolean isLiquidado() {
		return this.liquidado;
	}

	public void setLiquidado(boolean liquidado) {
		this.liquidado = liquidado;
	}

	@Column(name = "tipo", nullable = false)
	public boolean isTipo() {
		return this.tipo;
	}

	public void setTipo(boolean tipo) {
		this.tipo = tipo;
	}

	@Column(name = "valor", nullable = false, precision = 10, scale = 0)
	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vencimento", nullable = false, length = 19)
	public Date getVencimento() {
		return this.vencimento;
	}

	public void setVencimento(Date vencimento) {
		this.vencimento = vencimento;
	}

}
