package br.com.financeiro.pojo;

// default package
// Generated 10/11/2014 22:21:36 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Uf generated by hbm2java
 */
@Entity
@Table(name = "uf")
public class Uf implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String sigla;
	private String nome;
	private int codigo;
	private Set<Municipio> municipios = new HashSet<>(0);

	public Uf() {
	}

	public Uf(String sigla, String nome, int codigo) {
		this.sigla = sigla;
		this.nome = nome;
		this.codigo = codigo;
	}

	public Uf(String sigla, String nome, int codigo, Set<Municipio> municipios) {
		this.sigla = sigla;
		this.nome = nome;
		this.codigo = codigo;
		this.municipios = municipios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sigla", nullable = false, length = 2)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codigo", nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uf")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}
	
	@Override
	public String toString() {	
		return getSigla();
	}

}
